name: flat10
channels:
  - chrisroadmap
  - conda-forge
dependencies:
  - fair==2.1.3
  - jupyter
  - nbstripout
  - matplotlib
  - numpy
  - pandas
  - pooch
  - seaborn
  - scipy
  - tqdm
  - xarray
